model_name_or_path: Seedboxai/sparse_llama_3.1-8b-sft-distilled
model_revision: main
use_flash_attn: true
gradient_checkpointing: true
dataset_mixer:
  #HuggingFaceH4/ultrafeedback_binarized: 1.0 # handbook, Num examples = 60189
  allenai/llama-3.1-tulu-3-8b-preference-mixture: 1.0  # Num examples = 262824
#max_train_samples: 100
tokenizer_name: Seedboxai/sparse_llama_3.1-8b-sft-distilled
use_slow_tokenizer: true
max_seq_length: 1024  #'best':2048, qlora:1024, handbook:1024
preprocessing_num_workers: 128  #'best':16  qlora: 128 handbook:12
per_device_train_batch_size: 2
gradient_accumulation_steps: 8 # designed for 8 GPUs, so batch size 128, handbook:4
learning_rate: 1.0e-4 #'best': 5.0e-7, qlora:1.0e-4 , handbook: 5.0e-6
lr_scheduler_type: cosine # linear, handbook: cosine 
warmup_ratio: 0.03 #'best': 0.1 qlora:0.03, handbook: 0.1
weight_decay: 0.0
num_train_epochs: 5 #'best':1, qlora:5, handbook: 1
output_dir: output/Sparse8B_Distilled_TO_DPO_Lora
with_tracking: true
report_to:
  - wandb
logging_steps: 1
dpo_loss_type: dpo_norm
dpo_beta: 5 #'best':5
checkpointing_steps: 2000

# LoRA arguments
use_lora: true
use_qlora: false
lora_rank: 128 #qlora:64   handbook:128
lora_alpha: 128 # qlora:16  handbook:128
lora_dropout: 0.1 # qlora:0.1 handbook:0.05

hf_entity : "WenWW"
hf_repo_id: "Sparse8B_Distilled_TO_DPO_Lora"
hf_repo_revision: "main"
push_to_hub: true
