model_name_or_path: neuralmagic/Sparse-Llama-3.1-8B-2of4
model_revision: main
use_flash_attn: true
gradient_checkpointing: true
tokenizer_name: neuralmagic/Sparse-Llama-3.1-8B-2of4
use_slow_tokenizer: false
dataset_name: trl-internal-testing/tldr-preference-trl-style
#HuggingFaceH4/ultrafeedback_binarized
max_seq_length: 1024
max_train_samples: 100
preprocessing_num_workers: 16 #128
per_device_train_batch_size: 1
gradient_accumulation_steps: 4 
learning_rate: 5.0e-7
lr_scheduler_type: linear
warmup_ratio: 0.03
weight_decay: 0.0
num_train_epochs: 1
output_dir: output/dpo_qlora_2/
with_tracking: true
report_to:
  - wandb
logging_steps: 1
checkpointing_steps: 1000
#keep_last_n_checkpoints: 3
try_launch_beaker_eval_jobs: false
hf_entity : "WenWW"
hf_repo_id: "sparse_Llama_8B_2of4_DPO_qlora_test"
hf_repo_revision: "main"
push_to_hub: true

use_lora: true
use_qlora: true
lora_rank: 64
lora_alpha: 16
lora_dropout: 0.1