model_name_or_path:  neuralmagic/Sparse-Llama-3.1-8B-2of4
model_revision: main
use_flash_attn: true
gradient_checkpointing: true
dataset_name: HuggingFaceH4/ultrafeedback_binarized
tokenizer_name:  neuralmagic/Sparse-Llama-3.1-8B-2of4
use_slow_tokenizer: false
max_seq_length: 1024
preprocessing_num_workers: 128
per_device_train_batch_size: 1
gradient_accumulation_steps: 16 # designed for 8 GPUs, so batch size 128
learning_rate: 1e-4
lr_scheduler_type: linear
warmup_ratio: 0.03
weight_decay: 0.0
num_train_epochs: 5
output_dir: output/dpo_8b_qlora
with_tracking: true
report_to:
  - wandb
logging_steps: 1
use_lora: false
dpo_loss_type: dpo_norm
dpo_beta: 5
checkpointing_steps: 1000
use_lora: true
use_qlora: true
lora_rank: 64
lora_alpha: 16
lora_dropout: 0.1
hf_entity : "WenWW"
hf_repo_id: "sparse_Llama_8B_2of4_DPO_qlora_test"
hf_repo_revision: "main"
push_to_hub: true
